name: ⭐ 意见与建议
description: UltiTools 5 现已不接受任何的新功能请求，请前往 UltiTools 6 仓库，点击右侧按钮来查看详情
labels: enhancement 新功能请求
body:
  - type: markdown
    attributes:
      value: |
        非常感谢你能够来为这个插件提出意见，目前所有的开发工作都已经转到了UltiTools 6.0，**所以暂时5.0版本除了修复bug以外暂时不会更新新的内容**。
        请前往 UltiTools-Reborn 仓库来提交: https://github.com/UltiKits/UltiTools-Reborn/issues
        打开的所有新功能请求相关的 Issue 都将会被锁定。
  - type: checkboxes
    id: force
    attributes:
      label: 我不管
      options:
        - label: 我就是要打开一个这样的Issue，即使会被自动锁定
          required: true
