name: CI Build

on:
  push:
    branches: 
      - master
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '.github/**'
      - '.**'
  pull_request:
      paths-ignore:
      - 'doc/**'
      - '**.md'
      - '.github/**'
      - '.**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload built jar
      if: ${{ !github.event.pull_request }}
      uses: actions/upload-artifact@v3
      with:
        name: UltiTools
        path: target/UltiTools-**.jar
